[package]
name = "machine-vision-formats"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"
categories = ["no-std", "data-structures", "hardware-support", "multimedia::images"]

[features]
default=["std"]

std=[]
alloc=[]
